admin:
   resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
   prefix: /admin

_sonata_admin:
   resource: .
   type: sonata_admin
   prefix: /admin

app_joboard:
    resource: "@AppJoboardBundle/Resources/config/routing.yml"
    prefix:   /

burut_menu:
    resource: "@BurutMenuBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
