app_joboard:
    resource: "@AppJoboardBundle/Resources/config/routing.yml"
    prefix:   /

burut_menu:
    resource: "@BurutMenuBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
