# src/App/JoboardBundle/Resources/config/routing/affiliate.yml

app_affiliate_new:
   pattern:  /new
   defaults: { _controller: "AppJoboardBundle:Affiliate:new" }

app_affiliate_create:
   pattern: /create
   defaults: { _controller: "AppJoboardBundle:Affiliate:create" }
   requirements: { _method: post }

app_affiliate_wait:
   pattern: /wait
   defaults: { _controller: "AppJoboardBundle:Affiliate:wait" }
