app_job:
    path:     /
    defaults: { _controller: "AppJoboardBundle:Job:index" }

app_job_show:
    pattern:  /{company}/{location}/{id}/{position}/
    defaults: { _controller: "AppJoboardBundle:Job:show" }
    requirements:
        id:  \d+

app_job_new:
    path:     /new
    defaults: { _controller: "AppJoboardBundle:Job:new" }

app_job_create:
    path:     /create
    defaults: { _controller: "AppJoboardBundle:Job:create" }
    methods:  POST

app_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "AppJoboardBundle:Job:edit" }

app_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "AppJoboardBundle:Job:update" }
    requirements: { _method: post|put }

app_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "AppJoboardBundle:Job:delete" }
    requirements: { _method: post|delete }

app_job_show:
    pattern:  /{company}/{location}/{id}/{position}/
    defaults: { _controller: "AppJoboardBundle:Job:show" }
    requirements:
        id:  \d+

app_job_preview:
    pattern:  /{company}/{location}/{token}/{position}/
    defaults: { _controller: "AppJoboardBundle:Job:preview" }
    requirements:
        token:  \w+

app_job_publish:
    pattern:  /{token}/publish/
    defaults: { _controller: "AppJoboardBundle:Job:publish" }
    requirements: { _method: post, token: \w+ }

app_job_extend:
   pattern:  /{token}/extend/
   defaults: { _controller: "AppJoboardBundle:Job:extend" }
   requirements: { _method: post }