# src/App/JoboardBundle/Resources/config/routing.yml

login:
  pattern:   /login
  defaults:  { _controller: AppJoboardBundle:Default:login }
login_check:
  pattern:   /login_check
logout:
   pattern: /logout

app_joboard_app_job:
    resource: "@AppJoboardBundle/Resources/config/routing/job.yml"
    prefix:   /app_job

app_joboard_homepage:
    pattern:  /
    defaults: { _controller: AppJoboardBundle:Job:index }

AppJoboardBundle_job:
    resource: "@AppJoboardBundle/Resources/config/routing/job.yml"
    prefix: /job

AppJoboardBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: AppJoboardBundle:Category:show, page: 1 }

AppJoboardBundle_api:
   pattern: /api/{token}/jobs.{_format}
   defaults: {_controller: "AppJoboardBundle:Api:list"}
   requirements:
       _format: xml|json|yaml

AppJoboardBundle_app_affiliate:
   resource: "@AppJoboardBundle/Resources/config/routing/affiliate.yml"
   prefix:   /affiliate